## 1. Membuat array 1D dengan 5 elemen acak

In [1]:
import numpy as np

In [2]:
number = [2,3,5,7,9]
new_number = np.array(number)
print(new_number)

[2 3 5 7 9]


## 2. Jumlah, rata-rata, minimum, dan maximum pada array

In [8]:
number = np.array([2,3,5,7,9])

size_num = np.size(number)
mean_num = np.mean(number)
min_num = np.min(number)
max_num = np.max(number)

print('Total elemen in array:',size_num)
print('Mean result in array:',mean_num)
print('The minimum element in array:',min_num)
print('The maximum element in array:',max_num)

Total elemen in array: 5
Mean result in array: 5.2
The minimum element in array: 2
The maximum element in array: 9


## 3. Membuat 2 array numpy 2D berukuran 3x3

In [18]:
value1 = np.array([[2,4,6],[1,7,3],[5,8,9]])
value2 = np.array([[1,3,5],[3,4,6],[7,9,8]])
print(value1)
print(value2)

[[2 4 6]
 [1 7 3]
 [5 8 9]]
[[1 3 5]
 [3 4 6]
 [7 9 8]]


## 4. Melakukan operasi matematika terhadap kedua array

In [19]:
total_value = value1 + value2
less_value = value1 - value2
multiple_value = value1 * value2
divide_value = value1 / value2

print(total_value)
print(less_value)
print(multiple_value)
print(divide_value)

[[ 3  7 11]
 [ 4 11  9]
 [12 17 17]]
[[ 1  1  1]
 [-2  3 -3]
 [-2 -1  1]]
[[ 2 12 30]
 [ 3 28 18]
 [35 72 72]]
[[2.         1.33333333 1.2       ]
 [0.33333333 1.75       0.5       ]
 [0.71428571 0.88888889 1.125     ]]


## 5. Menghitung nilai determinan dari salah satu array

In [20]:
np.linalg.det(value2)

26.99999999999999

## 6. Membuat array numpy 1D dengan 10 elemen

In [22]:
test = [1,2,3,4,5,6,7,8,9,10]
test_array = np.array(test)
print(test_array)

[ 1  2  3  4  5  6  7  8  9 10]


## 7. Menampilkan elemen dengan indeks genap

In [27]:
even_number = np.arange(2,11,2)
print(even_number)

[ 2  4  6  8 10]


## 8. Subset array numpy > 5

In [34]:
import numpy.ma as ma
test = [1,2,3,4,5,6,7,8,9,10]
test_array = np.array(test)
mask_value = ma.masked_less(test_array, 5)
print(mask_value)

[-- -- -- -- 5 6 7 8 9 10]


## 9. Array numpy 2D berukuran 4x4

In [42]:
new_data = np.array([[1,2,3,4],[5,6,7,8],[1,3,5,7],[2,4,6,5]])
new_data

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 3, 5, 7],
       [2, 4, 6, 5]])

### 10. Mencari nilai mean, standar deviasi, median, dan koefisien korelasi

In [48]:
new_mean = np.mean(new_data)
new_std = np.std(new_data)
new_median = np.median(new_data)
new_corcoef = np.corrcoef(new_data)

print(new_mean)
print(new_std)
print(new_median)
print(new_corcoef)

4.3125
2.1130176880471208
4.5
[[1.         1.         1.         0.83152184]
 [1.         1.         1.         0.83152184]
 [1.         1.         1.         0.83152184]
 [0.83152184 0.83152184 0.83152184 1.        ]]


### 11. Array numpy 1D bernilai 0 hingga 3.14 dengan interval 0.1

In [57]:
new_value = np.arange(0,3.14,0.1)
print(new_value)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1]


## 12. Mencari nilai trigonometri dalam array (sin,cos, dan tan)

In [58]:
np.sin(new_value)

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098, 0.89120736, 0.93203909, 0.96355819, 0.98544973,
       0.99749499, 0.9995736 , 0.99166481, 0.97384763, 0.94630009,
       0.90929743, 0.86320937, 0.8084964 , 0.74570521, 0.67546318,
       0.59847214, 0.51550137, 0.42737988, 0.33498815, 0.23924933,
       0.14112001, 0.04158066])

In [59]:
np.cos(new_value)

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [60]:
np.tan(new_value)

array([  0.        ,   0.10033467,   0.20271004,   0.30933625,
         0.42279322,   0.54630249,   0.68413681,   0.84228838,
         1.02963856,   1.26015822,   1.55740772,   1.96475966,
         2.57215162,   3.60210245,   5.79788372,  14.10141995,
       -34.23253274,  -7.69660214,  -4.28626167,  -2.92709751,
        -2.18503986,  -1.70984654,  -1.37382306,  -1.11921364,
        -0.91601429,  -0.7470223 ,  -0.60159661,  -0.47272763,
        -0.35552983,  -0.24640539,  -0.14254654,  -0.04161665])

## 13. Mencari nilai max dan min dari sin

In [64]:
sin_value = np.sin(new_value)
np.min(sin_value),np.max(sin_value)

(0.0, 0.9995736030415051)