In [2]:
import numpy as np
import random

In [30]:
# Random array 1D, 5 element
random_array = np.random.randint(1,11,5)
print(random_array)

[6 6 6 7 6]


In [33]:
# Calculate total, mean, min, max values.
print("Min:", random_array.min(),
      "Max:", random_array.max(), 
      "Mean:", random_array.mean(), 
      "Total:", random_array.sum())

Min: 6 Max: 7 Mean: 6.2 Total: 31


In [69]:
# 2D array random numbers size 3x3
a = np.random.randint(1,100,size=(3,3))
b = np.random.randint(1,10,size=(3,3))

print("a", a) 
      
print("\n b", b)

a [[88 49 50]
 [30 87 18]
 [97 72 55]]

 b [[1 1 8]
 [7 4 1]
 [5 8 5]]


In [70]:
a * b

array([[ 88,  49, 400],
       [210, 348,  18],
       [485, 576, 275]])

In [71]:
a+b

array([[ 89,  50,  58],
       [ 37,  91,  19],
       [102,  80,  60]])

In [72]:
a-b

array([[87, 48, 42],
       [23, 83, 17],
       [92, 64, 50]])

In [73]:
a/b

array([[88.        , 49.        ,  6.25      ],
       [ 4.28571429, 21.75      , 18.        ],
       [19.4       ,  9.        , 11.        ]])

In [76]:
#Determinant of a 3x3 matrix
np.linalg.det(a)

-2213.999999999975

In [83]:
#create 1D array in range 1 to 10 with 10 element
array1D =np.random.randint(1,11,10)
array1D

array([ 4,  3, 10,  3,  3,  6,  6,  5,  6,  2])

In [88]:
# Even number
print(array1D[array1D % 2 ==0])

[ 4 10  6  6  6  2]


In [89]:
# Array1D values > 5
print(array1D[array1D > 5 ])

[10  6  6  6]


In [102]:
# 2D array
array2D = np.random.randint(1,20,size=(4,4))
array2D

array([[ 6,  6,  2, 10],
       [16, 16,  5,  1],
       [ 7,  2,  4,  9],
       [ 6, 14, 15,  5]])

In [103]:
#mean
array2D.mean()

7.75

In [104]:
# Standart Deviation
np.std(array2D)

4.905354217587146

In [105]:
#Median
np.median(array2D)

6.0

In [112]:
# Correlation coefficients
np.corrcoef(array2D, rowvar=False)

array([[ 1.        ,  0.59726763, -0.20702087, -0.83025565],
       [ 0.59726763,  1.        ,  0.54770186, -0.90143345],
       [-0.20702087,  0.54770186,  1.        , -0.37014097],
       [-0.83025565, -0.90143345, -0.37014097,  1.        ]])

In [116]:
# 1D array form 0 to pi, with step 0.1
array_1D = np.arange(0, np.pi, 0.1)
array_1D

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1])

In [124]:
# Tan
tan_values = np.tan(array_1D)
tan_values

array([  0.        ,   0.10033467,   0.20271004,   0.30933625,
         0.42279322,   0.54630249,   0.68413681,   0.84228838,
         1.02963856,   1.26015822,   1.55740772,   1.96475966,
         2.57215162,   3.60210245,   5.79788372,  14.10141995,
       -34.23253274,  -7.69660214,  -4.28626167,  -2.92709751,
        -2.18503986,  -1.70984654,  -1.37382306,  -1.11921364,
        -0.91601429,  -0.7470223 ,  -0.60159661,  -0.47272763,
        -0.35552983,  -0.24640539,  -0.14254654,  -0.04161665])

In [125]:
# Cos
cos_values = np.cos(array_1D)
cos_values

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [126]:
# Sin
sin_values = np.sin(array_1D)
sin_values

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098, 0.89120736, 0.93203909, 0.96355819, 0.98544973,
       0.99749499, 0.9995736 , 0.99166481, 0.97384763, 0.94630009,
       0.90929743, 0.86320937, 0.8084964 , 0.74570521, 0.67546318,
       0.59847214, 0.51550137, 0.42737988, 0.33498815, 0.23924933,
       0.14112001, 0.04158066])

In [127]:
# Sin min and max values
np.min(sin_values), np.max(sin_values)

(0.0, 0.9995736030415051)

In [143]:
# Save array
np.save('array_sin.npy', sin_values)

In [145]:
# Loaded Array
Load_arr = np.load('array_sin.npy')
print(Load_arr)

[0.         0.09983342 0.19866933 0.29552021 0.38941834 0.47942554
 0.56464247 0.64421769 0.71735609 0.78332691 0.84147098 0.89120736
 0.93203909 0.96355819 0.98544973 0.99749499 0.9995736  0.99166481
 0.97384763 0.94630009 0.90929743 0.86320937 0.8084964  0.74570521
 0.67546318 0.59847214 0.51550137 0.42737988 0.33498815 0.23924933
 0.14112001 0.04158066]
