Soal Teori :
---

__1. Langkah-langkah untuk menginstal NumPy di environment Python :__

- Pastikan pip sudah terinstal dengan menjalankan kode di bawah ini.

In [ ]:
!pip --version

- Kemudian instal NumPy dengan menjalankan kode berikut.

In [ ]:
!pip install numpy

- Apabila sudah terinstal, kita dapa cek versi dengan menjalankan kode berikut.

In [ ]:
import numpy as np
print(np.__version__)

__2. Perintah untuk instal NumPy menggunakan pip :__

- Terminal 

In [ ]:
pip install numpy

- IPython Notebook

In [ ]:
!pip install numpy

__3. Cara memeriksa apakah NumPy sudah terinstal di sistem:__

- Dari terminal

Jalankan kode berikut. Jika terinstal maka akan terlihat informasi detail tentang NumPy tersebut.

In [ ]:
pip show numpy

- Dari IPython Notebook

Jalankan kode berikut.

In [ ]:
import numpy as np
print(np.__version__)

__4. Perbedaan instalasi NumPy dengan pip dan conda:__

pip merupakan standard package manager khusus untuk Python sedangkan conda meupakan package manager yang lebih universal yang bisa juga digunakan untuk package non-Python

__5. Cara membuat array NumPy satu dimensi :__

- Untuk membuat array NumPy satu dimensi dapat menggunakan fungsi ```numpy.array()``` , ```numpy.arrange()``` , ```numpy.linspace()```

__6. Perbedaan antara array NumPy satu dimensi dan list Python biasa :__

- Performa

Array NumPy memiliki performa yang lebih baik dari list Python.
- Tipe data

Tipe data pada array NumPy seragam sedangkan pada list dapat beragam.
- Ukuran dimensi

Array Numpy memiliki dimensi yang tetap sedangkan dimensi list Python lebih fleksibel.
- Fungsionalitas

NumPy menyediakan berbagai fungsi dan metode yang dioptimalkan untuk manipulasi dan analisis data numerik, seperti operasi aritmatika, statistik, pemotongan, penyaringan, dll. List Python memiliki sedikit fungsi bawaan untuk operasi data numerik, dan operasi aritmatika dilakukan secara elemen demi elemen.
- Memori

Array NumPy cenderung menggunakan lebih sedikit memori daripada list Python, karena elemen-elemennya disimpan secara berdampingan dalam memori tanpa ada penambahan overhead untuk tipe data Python yang tersimpan bersama dengan setiap elemen.

7. Cara untuk membuat array NumPy dua dimensi menggunakan list bersarang :

- Caranya adalah dengan menggukan fungsi ```numpy.array()```. Lihat contoh di bawah.

In [6]:
nested_list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [7]:
import numpy as np

In [8]:
my_array = np.array(nested_list)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

__8.  Fungsi dari atribut shape dalam array NumPy :__

Atribut shape dalam array NumPy memberikan informasi tentang dimensi dan ukuran array. Atribut shape adalah tuple yang menunjukkan jumlah elemen dalam setiap dimensi array.

9. Cara mengakses elemen tertentu dalam array NumPy :

Untuk mengakses elemen dalam array NumPy maka kita dapat melakukan indexing. Lihat kode berikut.

In [9]:
# syntax :
# <nama_var_array>[index_baris][index_kolom]

my_array[0][1]

2

__10. Perintah untuk menghitung jumlah elemen dalam array NumPy :__

In [10]:
np.size(my_array)

9

__11. Perbedaan antara np.zeros dan np.ones dalam konteks array NumPy :__

Perbedaan utama antara ```np.zeros``` dan ```np.ones``` adalah nilai awal yang digunakan dalam pembuatan array. ```np.zeros``` menghasilkan array dengan semua elemen nol, sedangkan ```np.ones``` menghasilkan array dengan semua elemen satu.

__12. Apa yang dimaksud dengan broadcasting dalam NumPy, dan mengapa hal itu berguna?__

Broadcasting adalah mekanisme dalam NumPy yang memungkinkan operasi aritmatika (seperti penambahan, pengurangan, perkalian, dll.) dilakukan pada array dengan bentuk yang berbeda atau ukuran yang tidak sama. Dalam broadcasting, NumPy secara otomatis menyesuaikan bentuk atau dimensi array yang lebih kecil agar sesuai dengan array yang lebih besar sehingga operasi aritmatika dapat dilakukan.

Konsep ini berguna karena memungkinkan kita untuk melakukan operasi aritmatika pada array NumPy dengan cara yang lebih fleksibel tanpa perlu menambahkan dimensi atau menyalin data, yang dapat menghemat memori dan meningkatkan kinerja. 

__13. Bagaimana cara melakukan operasi matematika dasar (penjumlahan, pengurangan, perkalian) antara dua array NumPy?__

Kita dapat melakukan operasi matematika dasar (penjumlahan, pengurangan, perkalian) antara dua array NumPy dengan menggunakan operator aritmatika standar (+, -, *) atau fungsi-fungsi NumPy yang sesuai.

___14. Perbedaan antara metode reshape dan resize dalam NumPy :___

Perbedaan utama antara reshape dan resize adalah dalam cara mereka memperlakukan array asli dan dalam penanganan bentuk. reshape mengembalikan array baru dengan bentuk yang diinginkan tanpa mengubah array asli, sementara resize mengubah array asli untuk memiliki bentuk yang baru.

___15.  menggabungkan dua array NumPy menjadi satu :___

- Menggunakan ```numpy.concatenate()```

Metode ```numpy.concatenate()``` digunakan untuk menggabungkan dua atau lebih array NumPy secara berdampingan, baik dalam satu dimensi maupun dalam dimensi yang ditentukan. 

In [11]:
import numpy as np

# Membuat dua array NumPy
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Menggabungkan dua array menjadi satu dalam satu dimensi
gabung = np.concatenate((arr1, arr2))

print("Hasil Penggabungan:")
print(gabung)

Hasil Penggabungan:
[1 2 3 4 5 6]


__16. slicing dalam konteks array NumPy dan cara menggunakannya :__

Slicing dalam konteks array NumPy mengacu pada proses memperoleh bagian atau sub-array dari array NumPy yang lebih besar dengan menentukan rentang indeks tertentu. Dengan menggunakan slicing, Anda dapat mengambil sebagian atau seluruh elemen dari array NumPy dengan cara yang sangat efisien.

Cara penggunaannya adalah seperti kode di bawah.

In [12]:
import numpy as np

# Membuat array NumPy
arr = np.array([1, 2, 3, 4, 5])

# Mengambil bagian dari array menggunakan slicing
sub_arr = arr[1:4]  # Mengambil elemen dari indeks 1 hingga indeks 3

print(sub_arr)  # Output: [2 3 4]

[2 3 4]


__17. Bagaimana cara menghitung rata-rata, median, dan standar deviasi dari array NumPy?__

- Menghitung Rata-rata:

-> Menggunakan fungsi ```numpy.mean()```
- Menghitung Median:

-> Menggunakan fungsi ```numpy.median()```
-  Menghitung Standar Deviasi:

-> Menggunakan fungsi ```numpy.std()```

__18. Kegunaan dari fungsi np.arange dalam NumPy :__

Fungsi ```np.arange()``` dalam NumPy digunakan untuk membuat array yang berisi urutan angka dalam suatu rentang tertentu. Rentang ini dapat ditentukan dengan memberikan nilai awal, nilai akhir, dan langkah (step) antara angka-angka dalam rentang tersebut.

__19. Cara menyimpan dan memuat array NumPy ke dan dari file :__

-> Menggunakan metode ```numpy.save()``` dan ```numpy.load()```

- menyimpan

In [13]:
import numpy as np

# Membuat array NumPy
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Menyimpan array ke dalam file 'array.npy'
np.save('array.npy', arr)

- Memuat

In [14]:
import numpy as np

# Memuat array dari file 'array.npy'
arr_loaded = np.load('array.npy')

print("Array yang Dimuat:")
print(arr_loaded)

Array yang Dimuat:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


---

Soal Praktikum
---

__1. Buatlah array NumPy 1D dengan 5 elemen bilangan bulat acak antara 1 hingga 10.__

In [16]:
import numpy as np

In [19]:
random_array = np.random.randint(1,11, size= 5) # bilangan acak 1 - 10
random_array

array([9, 9, 1, 1, 5])

__2. Hitung jumlah, rata-rata, nilai minimum, dan nilai maksimum dari array yang telah dibuat.__

In [22]:
# Jumlah
print(np.sum(random_array))

# Rata-rata
print(np.mean(random_array))

# Nilai minimum
print(np.min(random_array))

# Nilai maksimum
print(np.max(random_array))

25
5.0
1
9


______3. Buatlah dua buah array NumPy 2D dengan ukuran 3x3 yang berisi bilangan bulat acak.______

In [24]:
random_array_1 = np.random.randint(1,11, size= (3,3))
random_array_2 = np.random.randint(1,11, size= (3,3))

In [26]:
print(random_array_1)

[[6 1 5]
 [4 6 9]
 [4 3 5]]


In [27]:
print(random_array_2)

[[3 3 5]
 [9 3 9]
 [3 6 4]]


__4. Lakukan penjumlahan, pengurangan, perkalian, dan pembagian antara kedua array tersebut.__

In [28]:
# Penjumlahan
addition = random_array_1 + random_array_2
addition

array([[ 9,  4, 10],
       [13,  9, 18],
       [ 7,  9,  9]])

In [29]:
# Pengurangan
substaction = random_array_2 - random_array_1
substaction

array([[-3,  2,  0],
       [ 5, -3,  0],
       [-1,  3, -1]])

In [30]:
# Perkalian
multiplication = random_array_1 * random_array_2
multiplication

array([[18,  3, 25],
       [36, 18, 81],
       [12, 18, 20]])

In [31]:
# Pembagian
division = random_array_2/random_array_1
division

array([[0.5 , 3.  , 1.  ],
       [2.25, 0.5 , 1.  ],
       [0.75, 2.  , 0.8 ]])

__5. Hitung determinan dari salah satu array tersebut.__

In [32]:
print(np.linalg.det(random_array_1))

-26.000000000000004


__6. Buatlah array NumPy 1D dengan 10 elemen bilangan bulat dari 1 hingga 10.__

In [33]:
range_array = np.arange(1,11)
range_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

__7. Tampilkan elemen dengan indeks genap.__

In [34]:
elemen_genap = range_array[1::2]
print(elemen_genap)

[ 2  4  6  8 10]


__8. Ambil subset array yang hanya berisi nilai lebih dari 5.__

In [35]:
subset = range_array[range_array>5]
print(subset)

[ 6  7  8  9 10]


__9. Buatlah array NumPy 2D berukuran 4x4 dengan bilangan bulat acak.__

In [38]:
random_numpy = np.random.randint(1,11, size=(4,4))
random_numpy

array([[ 6,  5,  5,  3],
       [ 2,  5,  1, 10],
       [ 5, 10,  2,  3],
       [ 1,  1,  6,  5]])

__10. Hitung nilai rata-rata, standar deviasi, median, dan korelasi antar-kolom dari array tersebut.__

In [39]:
# Rata-rata
print(np.mean(random_numpy))

4.375


In [40]:
# Standar deviasi
print(np.std(random_numpy))

2.7357585785299112


In [41]:
# Median
print(np.median(random_numpy))

5.0


In [42]:
# Korelasi antar kolom
korelasi = np.corrcoef(random_numpy, rowvar= False)
korelasi

array([[ 1.        ,  0.66488997, -0.05882353, -0.65690351],
       [ 0.66488997,  1.        , -0.66488997, -0.28057851],
       [-0.05882353, -0.66488997,  1.        , -0.5297609 ],
       [-0.65690351, -0.28057851, -0.5297609 ,  1.        ]])

__11. Buatlah array NumPy 1D dengan nilai-nilai dari 0 hingga π dengan interval 0.1.__

In [43]:
pi_arr = np.arange(0, np.pi + 0.1, 0.1)
pi_arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2])

__12. Hitung nilai sin, cos, dan tan dari setiap elemen array tersebut.__

In [47]:
# sin
hasil_sin = np.sin(pi_arr)
hasil_sin

array([ 0.        ,  0.09983342,  0.19866933,  0.29552021,  0.38941834,
        0.47942554,  0.56464247,  0.64421769,  0.71735609,  0.78332691,
        0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414])

In [48]:
# cos
hasil_cos = np.cos(pi_arr)
hasil_cos

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515, -0.99829478])

In [49]:
# tan
hasil_tan = np.tan(pi_arr)
hasil_tan

array([  0.        ,   0.10033467,   0.20271004,   0.30933625,
         0.42279322,   0.54630249,   0.68413681,   0.84228838,
         1.02963856,   1.26015822,   1.55740772,   1.96475966,
         2.57215162,   3.60210245,   5.79788372,  14.10141995,
       -34.23253274,  -7.69660214,  -4.28626167,  -2.92709751,
        -2.18503986,  -1.70984654,  -1.37382306,  -1.11921364,
        -0.91601429,  -0.7470223 ,  -0.60159661,  -0.47272763,
        -0.35552983,  -0.24640539,  -0.14254654,  -0.04161665,
         0.05847385])

__13. Tampilkan nilai maksimum dan minimum dari hasil perhitungan sin.__

In [50]:
# max
print(np.max(hasil_sin))

0.9995736030415051


In [51]:
# min
print(np.min(hasil_sin))

-0.058374143427580086
